name: _layerlens_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - pkgs/layerlens
  - pkgs/layerlens/example
  - pkgs/seo_splash
  - pkgs/seo_splash_flutter
  - pkgs/tappable_text
  