//  Copyright 2023 Google LLC
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

import 'dart:io';
import 'model.dart';
import 'package:path/path.dart' as path;

class MdGenerator {
  final String rootDir;
  final SourceFolder sourceFolder;

  MdGenerator({
    required this.rootDir,
    required this.sourceFolder,
  });

  Future<void> generateFiles() async {
    await _generateFile(sourceFolder);
  }

  /// Recursively generates md files in source folders.
  Future<void> _generateFile(SourceFolder folder) async {
    final file =
        File(path.joinAll([rootDir, folder.fullName, 'DEPENDENCIES.md']));

    if (await file.exists()) {
      await file.delete();
    }

    final theContent = content(folder);
    if (theContent != null) {
      file.writeAsStringSync(theContent);
    }

    for (final node in folder.children.values) {
      if (node is SourceFolder) await _generateFile(node);
    }
  }

  static String? content(SourceFolder folder) {
    final items = <String>[];
    for (final consumer in folder.children.values) {
      for (final dep in consumer.siblingDependencies) {
        final isInversion = consumer.layer! > dep.layer!;
        final arrow = isInversion ? '--!-->' : '-->';
        items.add('${consumer.shortName}$arrow${dep.shortName};');
      }
    }

    if (items.isEmpty) return null;

    items.sort();
    final result = StringBuffer();

    result.writeln('<!---');
    result.writeln('Generated by https://github.com/polina-c/layerlens');
    result.writeln('Dependencies that create loop are markes with `!`.');
    result.writeln('-->');
    result.writeln('');
    result.writeln('```mermaid');
    result.writeln('flowchart TD;');
    result.writeln(items.join('\n'));
    result.writeln('```');
    result.writeln('');

    return result.toString();
  }
}
