//  Copyright 2023 Google LLC
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

import 'dart:io';

import 'package:glob/glob.dart';
import 'package:path/path.dart' as path;

import 'model.dart';

class MdGenerator {
  final String rootDir;
  final SourceFolder sourceFolder;
  final List<Glob> buildFilters;
  final bool failIfChanged;

  MdGenerator({
    required this.rootDir,
    required this.sourceFolder,
    required this.buildFilters,
    required this.failIfChanged,
  });

  Future<int> generateFiles() async {
    return await _generateFile(sourceFolder);
  }

  /// Recursively generates md files in source folders.
  ///
  /// Returns number of generated files.
  Future<int> _generateFile(SourceFolder folder) async {
    var result = 0;
    final file =
        File(path.joinAll([rootDir, folder.fullName, 'DEPENDENCIES.md']));

    if (await file.exists()) {
      await file.delete();
    }

    final theContent = content(folder);

    if (theContent == null) {
    } else {
      if (buildFilters.isEmpty ||
          buildFilters.any((filter) => filter.matches(folder.fullName))) {
        await file.writeAsString(theContent);
        result++;
      }
    }

    for (final node in folder.children.values) {
      if (node is SourceFolder) result += await _generateFile(node);
    }

    return result;
  }

  static String? content(SourceFolder folder) {
    final items = <String>[];
    for (final consumer in folder.children.values) {
      for (final dependency in consumer.siblingDependencies) {
        final inversion = isInversion(consumer, dependency);
        final arrow = inversion ? '--!-->' : '-->';
        items.add('${consumer.shortName}$arrow${dependency.shortName};');
      }
    }

    if (items.isEmpty) return null;

    items.sort();
    final result = StringBuffer();

    result.writeln('<!---');
    result.writeln('Generated by https://github.com/polina-c/layerlens');
    result.writeln(
      'Dependencies that create loops (inversions) are marked with `!`.',
    );
    result.writeln('-->');
    result.writeln('');
    result.writeln('```mermaid');
    result.writeln('flowchart TD;');
    result.writeln(items.join('\n'));
    result.writeln('```');
    result.writeln('');
    result.writeln('### Inversions');
    result.writeln(
      'In this folder: ${folder.localInversions}',
    );
    result.writeln('');
    result.writeln(
      'Including sub-folders: ${folder.totalInversions}',
    );
    result.writeln('');

    return result.toString();
  }
}
