name: Dart

on:
  schedule:
    # “At 00:00 (UTC) on Sunday.”
    - cron: '0 0 * * 0'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout

      - uses: dart-lang/setup-dart
        with:
          sdk: master

      - name: Version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Install example dependencies
        run: dart pub get
        working-directory: example

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
